import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Create admin user if ADMIN_EMAIL is set
  const adminEmail = process.env.ADMIN_EMAIL;
  if (adminEmail) {
    await prisma.user.upsert({
      where: { email: adminEmail },
      update: { isAdmin: true },
      create: {
        email: adminEmail,
        name: 'Admin',
        isAdmin: true,
      },
    });
    console.log(`Admin user ensured for ${adminEmail}`);
  }

  // ─── Industry 1: Biotech ──────────────────────────────────────────────────
  const biotech = await prisma.industry.upsert({
    where: { slug: 'biotech' },
    update: {},
    create: {
      name: 'Biotech / Life Sciences',
      slug: 'biotech',
      description: 'Clinical trials, FDA regulations, drug development, and the language of life sciences.',
      icon: '🧬',
      isActive: true,
    },
  });

  const biotechTerms = [
    {
      term: 'IND',
      fullForm: 'Investigational New Drug',
      definition: 'An application filed with the FDA before a new drug can be tested in humans.',
      exampleJargon: 'We filed the IND last month and expect to open our first clinical sites in Q1.',
      examplePlain: 'We submitted our application to the FDA to begin human testing last month and expect to start treating patients in Q1.',
      difficulty: 1,
    },
    {
      term: 'CRO',
      fullForm: 'Contract Research Organization',
      definition: 'A company hired by a sponsor to conduct clinical trials on its behalf.',
      exampleJargon: 'We\'re running the Phase 2 through a CRO to avoid building out our own clinical ops team.',
      examplePlain: 'We\'re using an outside company to run our clinical trial so we don\'t have to hire our own trial management staff.',
      difficulty: 1,
    },
    {
      term: 'GMP',
      fullForm: 'Good Manufacturing Practice',
      definition: 'FDA-regulated quality standards governing how drugs are produced.',
      exampleJargon: 'The facility passed its GMP inspection with zero critical findings.',
      examplePlain: 'The manufacturing facility passed its quality standards audit with no major problems.',
      difficulty: 1,
    },
    {
      term: 'GLP',
      fullForm: 'Good Laboratory Practice',
      definition: 'Quality and integrity standards for non-clinical laboratory studies.',
      exampleJargon: 'All toxicology studies were conducted under GLP to satisfy regulatory requirements.',
      examplePlain: 'All safety studies were done under official quality standards so the results would be accepted by regulators.',
      difficulty: 1,
    },
    {
      term: 'GCP',
      fullForm: 'Good Clinical Practice',
      definition: 'International ethical and scientific standards for clinical trials involving human participants.',
      exampleJargon: 'Every site is required to maintain GCP compliance throughout the trial.',
      examplePlain: 'Every clinical site must follow international ethical and scientific standards throughout the study.',
      difficulty: 1,
    },
    {
      term: 'SOP',
      fullForm: 'Standard Operating Procedure',
      definition: 'A documented, step-by-step instruction for carrying out a routine process consistently.',
      exampleJargon: 'The lab has an SOP for every process, so any technician can step in without retraining.',
      examplePlain: 'The lab has written step-by-step instructions for every process, so any technician can fill in without needing to be retrained.',
      difficulty: 1,
    },
    {
      term: 'API',
      fullForm: 'Active Pharmaceutical Ingredient',
      definition: 'The biologically active component in a drug that produces its therapeutic effect.',
      exampleJargon: 'The API is stable at room temperature, which simplifies our supply chain considerably.',
      examplePlain: 'The active drug ingredient is stable at room temperature, which makes our supply chain much simpler.',
      difficulty: 2,
    },
    {
      term: 'Phase 1',
      fullForm: null,
      definition: 'The first stage of human clinical testing, focused on safety and dosing rather than efficacy.',
      exampleJargon: 'Phase 1 data showed the drug was well-tolerated up to 200 mg with no dose-limiting toxicities.',
      examplePlain: 'Early human safety testing showed patients tolerated the drug well at up to 200 mg with no serious side effects.',
      difficulty: 1,
    },
    {
      term: 'Phase 2',
      fullForm: null,
      definition: 'A small trial in patients with the target disease to determine whether the drug has a beneficial effect.',
      exampleJargon: 'The Phase 2 readout showed a meaningful response rate in the target patient population.',
      examplePlain: 'The mid-stage clinical trial showed the drug helped a meaningful number of patients with the target disease.',
      difficulty: 1,
    },
    {
      term: 'Phase 3',
      fullForm: null,
      definition: 'A large-scale confirmatory clinical trial that forms the basis for regulatory approval.',
      exampleJargon: 'If Phase 3 replicates these results, we\'re looking at an NDA filing by year-end.',
      examplePlain: 'If the large-scale confirmatory trial replicates these results, we plan to apply for FDA approval by year-end.',
      difficulty: 2,
    },
    {
      term: 'IP',
      fullForm: 'Intellectual Property',
      definition: 'A company\'s portfolio of patents and other protected innovations — a key indicator of its value.',
      exampleJargon: 'Their IP estate covers the compound through 2038, giving them a long exclusivity runway.',
      examplePlain: 'Their patents on the compound run through 2038, giving them a long period without generic competition.',
      difficulty: 1,
    },
    {
      term: 'POC',
      fullForm: 'Proof of Concept',
      definition: 'Early experimental evidence that a therapeutic approach works as hypothesized.',
      exampleJargon: 'The mouse model gave us POC that the mechanism actually works in vivo.',
      examplePlain: 'The mouse experiment gave us early evidence that the biological approach works in a living organism.',
      difficulty: 1,
    },
    {
      term: 'KOL',
      fullForm: 'Key Opinion Leader',
      definition: 'A respected clinician whose expertise shapes prescribing practices in their field.',
      exampleJargon: 'We briefed three KOLs before the conference to align on how they\'d discuss the data.',
      examplePlain: 'We briefed three leading physicians before the conference to make sure they were ready to discuss our trial results.',
      difficulty: 2,
    },
    {
      term: 'BLA',
      fullForm: 'Biologic License Application',
      definition: 'The formal FDA submission required to bring a biologic drug to market.',
      exampleJargon: 'The BLA is on track for a December submission based on the current data package.',
      examplePlain: 'Our application to bring the biologic drug to market is on track for a December submission.',
      difficulty: 2,
    },
    {
      term: 'NDA',
      fullForm: 'New Drug Application',
      definition: 'The formal FDA submission required to bring a small-molecule drug to market.',
      exampleJargon: 'The FDA accepted our NDA for review and set a PDUFA date of March 15.',
      examplePlain: 'The FDA accepted our drug approval application and set a review deadline of March 15.',
      difficulty: 2,
    },
    {
      term: 'IRB',
      fullForm: 'Institutional Review Board',
      definition: 'An independent committee that protects the rights and welfare of clinical trial participants.',
      exampleJargon: 'The IRB approved the amended protocol within three weeks.',
      examplePlain: 'The ethics review committee approved the updated study plan within three weeks.',
      difficulty: 2,
    },
    {
      term: 'CRA',
      fullForm: 'Clinical Research Associate',
      definition: 'A professional who monitors trial sites to ensure data integrity and protocol compliance.',
      exampleJargon: 'The CRA flagged two source document discrepancies during the site visit last week.',
      examplePlain: 'The clinical trial monitor found two data inconsistencies when she visited the trial site last week.',
      difficulty: 2,
    },
    {
      term: 'CMC',
      fullForm: 'Chemistry, Manufacturing and Controls',
      definition: 'The section of a drug application describing the drug\'s composition, how it\'s made, and how quality is ensured.',
      exampleJargon: 'The CMC section was the most labor-intensive part of the IND package.',
      examplePlain: 'The section describing the drug\'s composition, manufacturing process, and quality controls was the most work-intensive part of our FDA application.',
      difficulty: 3,
    },
    {
      term: 'I-O',
      fullForm: 'Immuno-Oncology',
      definition: 'An area of cancer research that uses the body\'s own immune system to attack tumors.',
      exampleJargon: 'The company\'s entire pipeline is focused on I-O, betting that immune-based approaches will dominate oncology.',
      examplePlain: 'The company\'s entire pipeline is focused on cancer immunotherapy, betting that treatments using the body\'s immune system will dominate cancer care.',
      difficulty: 2,
    },
    {
      term: 'HTA',
      fullForm: 'Health Technology Assessment',
      definition: 'A systematic evaluation of the clinical and economic value of a new treatment to inform reimbursement decisions.',
      exampleJargon: 'NICE conducted an HTA and determined the drug wasn\'t cost-effective at the proposed list price.',
      examplePlain: 'The UK health authority conducted a formal evaluation and determined the drug wasn\'t worth its cost at the proposed price.',
      difficulty: 3,
    },
    {
      term: 'SUSAR',
      fullForm: 'Suspected Unexpected Serious Adverse Reaction',
      definition: 'A severe, unanticipated patient safety event that must be reported to regulators rapidly.',
      exampleJargon: 'The site reported a SUSAR within 24 hours, triggering an immediate safety review.',
      examplePlain: 'The trial site reported an unexpected serious patient safety event within 24 hours, triggering an immediate safety review.',
      difficulty: 3,
    },
    {
      term: 'CRADA',
      fullForm: 'Cooperative Research and Development Agreement',
      definition: 'A formal partnership between two organizations — often a biotech and a government agency — to jointly develop a technology.',
      exampleJargon: 'We signed a CRADA with the NIH to share resources on the combination therapy program.',
      examplePlain: 'We signed a formal partnership agreement with the NIH to share resources on developing a combination treatment.',
      difficulty: 3,
    },
    {
      term: 'CMO',
      fullForm: 'Contract Manufacturing Organization',
      definition: 'A company hired to manufacture a drug product on behalf of a sponsor.',
      exampleJargon: 'We selected a CMO in Ireland to manufacture clinical supply for the Phase 2.',
      examplePlain: 'We selected a contract manufacturer in Ireland to make the drug supply for our clinical trial.',
      difficulty: 2,
    },
    {
      term: 'PK/PD',
      fullForm: 'Pharmacokinetics / Pharmacodynamics',
      definition: 'How the body processes a drug (PK) and how the drug affects the body (PD).',
      exampleJargon: 'The PK/PD modeling suggests twice-daily dosing is optimal for maintaining therapeutic levels.',
      examplePlain: 'Our analysis of how the body processes the drug and how the drug affects the body suggests twice-daily dosing is best.',
      difficulty: 3,
    },
    {
      term: 'Top-line data',
      fullForm: null,
      definition: 'The first high-level results reported from a clinical trial — typically efficacy and safety headlines.',
      exampleJargon: 'Top-line data from the Phase 3 showed the primary endpoint was missed.',
      examplePlain: 'The first high-level results from our large trial showed the main goal of the study was not achieved.',
      difficulty: 2,
    },
    {
      term: 'AE',
      fullForm: 'Adverse Event',
      definition: 'Any undesirable medical occurrence in a patient enrolled in a clinical trial, whether or not related to the drug.',
      exampleJargon: 'Patients in the treatment arm reported more AEs than placebo, primarily GI-related.',
      examplePlain: 'Patients receiving the drug reported more unwanted medical events than those on placebo, mostly stomach-related.',
      difficulty: 1,
    },
    {
      term: 'SAE',
      fullForm: 'Serious Adverse Event',
      definition: 'An adverse event resulting in death, hospitalization, or disability — requires expedited reporting to regulators.',
      exampleJargon: 'The investigator reported an SAE of severe hepatotoxicity that required hospitalization.',
      examplePlain: 'The investigator reported a serious safety event of severe liver damage that required the patient to be hospitalized.',
      difficulty: 2,
    },
    {
      term: 'Protocol',
      fullForm: null,
      definition: 'The detailed written plan governing how a clinical trial is conducted, including objectives, design, and analysis methodology.',
      exampleJargon: 'Any deviation from the protocol must be documented and submitted to the IRB.',
      examplePlain: 'Any departure from the approved study plan must be documented and submitted to the ethics review committee.',
      difficulty: 1,
    },
    {
      term: 'Endpoint',
      fullForm: null,
      definition: 'A measurable outcome used to evaluate whether a drug is working in a clinical trial.',
      exampleJargon: 'The primary endpoint is overall survival at 24 months.',
      examplePlain: 'The main outcome we\'re measuring is whether patients are still alive at 24 months.',
      difficulty: 1,
    },
    {
      term: 'Placebo',
      fullForm: null,
      definition: 'An inactive substance given to the control group in a trial so that neither group knows who received the real drug.',
      exampleJargon: 'Patients receiving the placebo showed no improvement across any of the secondary endpoints.',
      examplePlain: 'Patients receiving the inactive pill showed no improvement on any of the secondary measures.',
      difficulty: 1,
    },
    {
      term: 'Double blind',
      fullForm: null,
      definition: 'A trial design in which neither the patient nor the investigator knows who received the drug versus placebo.',
      exampleJargon: 'The double blind design ensures neither patients nor doctors know who received the active drug.',
      examplePlain: 'The study design ensures neither patients nor doctors know who is taking the real drug versus an inactive pill.',
      difficulty: 2,
    },
    {
      term: 'RCT',
      fullForm: 'Randomized Controlled Trial',
      definition: 'The gold-standard study design in which patients are randomly assigned to treatment or control groups.',
      exampleJargon: 'Only an RCT can establish causation, not just correlation.',
      examplePlain: 'Only a study where patients are randomly assigned to treatment or placebo can prove the drug is actually causing the benefit.',
      difficulty: 2,
    },
    {
      term: 'Biomarker',
      fullForm: null,
      definition: 'A measurable biological indicator used to track disease progression or predict treatment response.',
      exampleJargon: 'The team identified a biomarker that predicts which patients will respond best to the drug.',
      examplePlain: 'The team found a measurable biological signal that predicts which patients will benefit most from the drug.',
      difficulty: 2,
    },
    {
      term: 'Biosimilar',
      fullForm: null,
      definition: 'A biologic drug highly similar to an approved reference biologic, with no clinically meaningful differences in safety or efficacy.',
      exampleJargon: 'Two biosimilars entered the market after the reference biologic\'s patent expired, cutting our market share.',
      examplePlain: 'Two similar versions of the original biologic drug entered the market after the patent expired, cutting into our sales.',
      difficulty: 2,
    },
    {
      term: 'Fast Track',
      fullForm: null,
      definition: 'An FDA designation that accelerates review for drugs treating serious conditions with unmet medical need.',
      exampleJargon: 'The drug received Fast Track designation, which means rolling review and more frequent FDA meetings.',
      examplePlain: 'The FDA designated the drug as a priority, giving us more frequent regulatory meetings and allowing us to submit data as it becomes available.',
      difficulty: 2,
    },
    {
      term: 'Breakthrough Therapy',
      fullForm: null,
      definition: 'An FDA designation for drugs showing early clinical evidence of substantial improvement over existing therapies.',
      exampleJargon: 'Breakthrough Therapy designation gave us intensive FDA guidance that shaved months off our development timeline.',
      examplePlain: 'The FDA\'s top priority designation gave us intensive regulatory guidance that shortened our development timeline significantly.',
      difficulty: 3,
    },
    {
      term: 'Orphan Drug',
      fullForm: null,
      definition: 'An FDA designation for drugs targeting rare diseases affecting fewer than 200,000 US patients, providing development incentives.',
      exampleJargon: 'Orphan Drug designation comes with seven-year market exclusivity and a 50% tax credit on clinical trial costs.',
      examplePlain: 'The rare disease drug designation gives us seven years without generic competition and a 50% tax credit on clinical testing costs.',
      difficulty: 2,
    },
    {
      term: 'PDUFA date',
      fullForm: 'Prescription Drug User Fee Act date',
      definition: 'The FDA\'s target deadline for completing its review of a drug application — effectively the approval decision date.',
      exampleJargon: 'The PDUFA date is August 22nd — that\'s when we find out whether we have an approved drug.',
      examplePlain: 'The FDA\'s internal review deadline is August 22nd — that\'s the day we expect to hear whether the drug is approved.',
      difficulty: 3,
    },
    {
      term: 'DSMB',
      fullForm: 'Data Safety Monitoring Board',
      definition: 'An independent committee that periodically reviews unblinded safety and efficacy data to protect trial participants.',
      exampleJargon: 'The DSMB conducted an unblinded interim review and recommended the trial continue as planned.',
      examplePlain: 'The independent safety committee looked at unblinded data midway through the trial and recommended it continue without changes.',
      difficulty: 3,
    },
    {
      term: 'SAP',
      fullForm: 'Statistical Analysis Plan',
      definition: 'A pre-specified document detailing exactly how trial data will be analyzed — written before unblinding.',
      exampleJargon: 'The SAP was finalized and locked before we unblinded the data to prevent post-hoc analysis.',
      examplePlain: 'The plan for how we\'d analyze the data was finalized and locked before anyone saw which patients received the drug.',
      difficulty: 3,
    },
    {
      term: 'ICH',
      fullForm: 'International Council for Harmonisation',
      definition: 'The global body that sets unified technical standards for pharmaceutical development across regulatory regions.',
      exampleJargon: 'The study was conducted in accordance with ICH E6(R2) guidelines.',
      examplePlain: 'The study followed the internationally harmonized standards for conducting ethical clinical trials.',
      difficulty: 2,
    },
    {
      term: 'ADME',
      fullForm: 'Absorption, Distribution, Metabolism, Excretion',
      definition: 'The four processes determining how a drug moves through and is eliminated from the body.',
      exampleJargon: 'The team conducted ADME studies before advancing the compound into human trials.',
      examplePlain: 'The team ran tests to understand how the body absorbs, distributes, breaks down, and eliminates the drug before starting human testing.',
      difficulty: 2,
    },
    {
      term: 'AUC',
      fullForm: 'Area Under the Curve',
      definition: 'A pharmacokinetic measure of total drug exposure in the bloodstream over time.',
      exampleJargon: 'The AUC for the 100 mg dose was twice that of the 50 mg dose, confirming linear pharmacokinetics.',
      examplePlain: 'The total drug exposure in the bloodstream at the 100 mg dose was twice that of the 50 mg dose, confirming the drug behaves predictably.',
      difficulty: 3,
    },
    {
      term: 'Adaptive design',
      fullForm: null,
      definition: 'A clinical trial design allowing pre-specified modifications — such as dropping arms or changing dose — based on interim data.',
      exampleJargon: 'We built an adaptive design into the protocol, allowing us to drop the low-dose arm if interim data was negative.',
      examplePlain: 'We built the ability to make pre-approved changes into our study plan, like dropping a lower-dose group if early data suggested it wasn\'t working.',
      difficulty: 3,
    },
    {
      term: 'Informed consent',
      fullForm: null,
      definition: 'The documented process by which a participant voluntarily agrees to a trial after being fully briefed on its risks and purpose.',
      exampleJargon: 'All participants must complete informed consent before any study procedures begin.',
      examplePlain: 'All participants must sign a document confirming they understand the trial\'s risks and voluntarily agree to participate before any study activities start.',
      difficulty: 1,
    },
    {
      term: 'Protocol deviation',
      fullForm: null,
      definition: 'Any departure from the approved study protocol — must be documented and, if significant, reported to the IRB.',
      exampleJargon: 'Three protocol deviations were identified during the site audit — two minor, one significant.',
      examplePlain: 'Three departures from the approved study plan were found during the audit — two minor and one serious enough to report to the ethics committee.',
      difficulty: 2,
    },
    {
      term: 'Pharmacovigilance',
      fullForm: null,
      definition: 'The science of detecting, assessing, and preventing adverse drug effects after a drug reaches the market.',
      exampleJargon: 'The pharmacovigilance team monitors for adverse events across the entire marketed portfolio.',
      examplePlain: 'The safety monitoring team watches for harmful drug effects across all products already on the market.',
      difficulty: 3,
    },
    {
      term: 'Compassionate use',
      fullForm: null,
      definition: 'An FDA pathway allowing patients with serious conditions to access unapproved investigational drugs outside of clinical trials.',
      exampleJargon: 'A pediatric patient who didn\'t qualify for the trial received the drug under compassionate use.',
      examplePlain: 'A child who didn\'t meet the criteria for the clinical trial was allowed to receive the drug through a special FDA program for patients with serious conditions.',
      difficulty: 2,
    },
    {
      term: 'CBER',
      fullForm: 'Center for Biologics Evaluation and Research',
      definition: 'The FDA division regulating biologic products including vaccines, blood products, and gene therapies.',
      exampleJargon: 'The gene therapy was reviewed by CBER, not CDER, because it\'s classified as a biologic.',
      examplePlain: 'The gene therapy was reviewed by the FDA\'s biologics division rather than its conventional drug division because of how it\'s classified.',
      difficulty: 2,
    },
    {
      term: 'CDER',
      fullForm: 'Center for Drug Evaluation and Research',
      definition: 'The FDA division regulating conventional small-molecule pharmaceutical products.',
      exampleJargon: 'CDER approved the small-molecule drug after a standard 10-month review.',
      examplePlain: 'The FDA\'s drug review division approved the conventional pill after a standard 10-month review.',
      difficulty: 2,
    },
    {
      term: 'Label',
      fullForm: null,
      definition: 'The official FDA-approved prescribing information for a drug, detailing approved uses, dosing, warnings, and contraindications.',
      exampleJargon: 'The label includes a black box warning for hepatotoxicity based on post-market data.',
      examplePlain: 'The official prescribing information includes the FDA\'s most serious type of warning for liver damage, based on data collected after the drug was already on the market.',
      difficulty: 2,
    },
    {
      term: 'ITT',
      fullForm: 'Intent to Treat',
      definition: 'An analysis approach that includes all randomized patients in the group they were assigned to regardless of whether they completed treatment.',
      exampleJargon: 'The primary analysis was conducted on an ITT basis — all 400 randomized patients were included.',
      examplePlain: 'The main analysis included all 400 patients in the groups they were randomly assigned to, regardless of whether they completed the full treatment.',
      difficulty: 3,
    },
    {
      term: 'Cohort',
      fullForm: null,
      definition: 'A defined group of study participants who share a common characteristic or are followed over the same time period.',
      exampleJargon: 'The study enrolled a cohort of patients who were all newly diagnosed within the past six months.',
      examplePlain: 'The study enrolled a group of patients who all shared the same characteristic: being newly diagnosed within the past six months.',
      difficulty: 1,
    },
    {
      term: 'Basket trial',
      fullForm: null,
      definition: 'A clinical trial testing a single drug against multiple diseases or tumor types that share the same genetic mutation.',
      exampleJargon: 'The basket trial enrolled patients with six different tumor types, all sharing the same EGFR mutation.',
      examplePlain: 'The trial enrolled patients with six different types of cancer, all sharing the same genetic mutation, to see if one drug could treat all of them.',
      difficulty: 3,
    },
    {
      term: 'Compound',
      fullForm: null,
      definition: 'A molecule or drug candidate under investigation — used before it has a brand name.',
      exampleJargon: 'The compound showed strong activity in the cell-line assays, so we\'re advancing it into animal studies.',
      examplePlain: 'The experimental molecule showed strong effects in lab cell tests, so we\'re moving it into animal studies.',
      difficulty: 1,
    },
    {
      term: 'Pipeline',
      fullForm: null,
      definition: 'A company\'s portfolio of drug candidates at various stages of development.',
      exampleJargon: 'The company\'s pipeline has three candidates in Phase 2 and one in Phase 3.',
      examplePlain: 'The company has three drugs in mid-stage clinical testing and one in late-stage testing.',
      difficulty: 1,
    },
    {
      term: 'Co-Co',
      fullForm: null,
      definition: 'A partnership in which two companies share 50/50 in the development, marketing, and sales of a product or technology.',
      exampleJargon: 'We structured the deal as a Co-Co, sharing all development costs and profits equally with our partner.',
      examplePlain: 'We structured the deal as a 50/50 partnership, sharing all development costs and future profits equally.',
      difficulty: 3,
    },
    {
      term: 'ROFR',
      fullForm: 'Right of First Refusal',
      definition: 'A contractual right giving one party the first opportunity to advance their ownership of a technology before it can be offered elsewhere.',
      exampleJargon: 'We granted the larger pharma a ROFR on any out-licensing of the compound before offering it to third parties.',
      examplePlain: 'We gave the larger pharmaceutical company the right to be first in line to license the drug before we could offer it to anyone else.',
      difficulty: 3,
    },
    {
      term: 'Blinded study',
      fullForm: null,
      definition: 'A clinical trial in which participants and/or investigators do not know who received the drug versus the placebo.',
      exampleJargon: 'The blinded study design prevents investigator bias from affecting how adverse events are assessed.',
      examplePlain: 'Not telling investigators who got the drug prevents them from unconsciously reporting side effects differently between groups.',
      difficulty: 2,
    },
    {
      term: 'Regulatory submission',
      fullForm: null,
      definition: 'A formal package of documents sent to a regulatory agency to request approval for a drug or clinical trial.',
      exampleJargon: 'The regulatory submission was 50,000 pages across 14 modules.',
      examplePlain: 'The formal package of documents sent to the FDA requesting drug approval was 50,000 pages across 14 sections.',
      difficulty: 1,
    },
  ];

  for (const t of biotechTerms) {
    await prisma.term.upsert({
      where: { id: `biotech-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}` },
      update: {},
      create: {
        id: `biotech-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        industryId: biotech.id,
        ...t,
      },
    });
  }
  console.log(`Seeded ${biotechTerms.length} biotech terms`);

  // ─── Industry 2: Ad Agency ────────────────────────────────────────────────
  const adAgency = await prisma.industry.upsert({
    where: { slug: 'ad-agency' },
    update: {},
    create: {
      name: 'Ad Agency',
      slug: 'ad-agency',
      description: 'Media buying, creative, campaign metrics, and the language of advertising and marketing.',
      icon: '📢',
      isActive: true,
    },
  });

  const adAgencyTerms = [
    {
      term: 'Brief',
      fullForm: null,
      definition: 'A document outlining a campaign\'s objectives, target audience, messaging, deliverables, and budget.',
      exampleJargon: 'The client approved the brief yesterday, so creative can finally start concepting.',
      examplePlain: 'The client approved the project outline yesterday, so the creative team can finally start developing ideas.',
      difficulty: 1,
    },
    {
      term: 'Creative',
      fullForm: null,
      definition: 'The actual ad content — copy, design, or video — produced by the agency.',
      exampleJargon: 'The client loved the creative — we\'re going into production on all three executions.',
      examplePlain: 'The client loved the ad content we made — we\'re moving forward to produce all three versions.',
      difficulty: 1,
    },
    {
      term: 'Copy',
      fullForm: null,
      definition: 'The written words in any advertisement, from headlines to body text.',
      exampleJargon: 'The copy needs to be punchy — we have three seconds to hook someone scrolling their feed.',
      examplePlain: 'The written words need to be punchy — we have three seconds to grab someone\'s attention while they\'re scrolling.',
      difficulty: 1,
    },
    {
      term: 'Concept',
      fullForm: null,
      definition: 'A visualization or idea communicating a campaign\'s core creative direction before full production begins.',
      exampleJargon: 'We\'ll present three concepts on Thursday and let the client choose the direction.',
      examplePlain: 'We\'ll show three different creative ideas on Thursday and let the client choose which one to develop fully.',
      difficulty: 1,
    },
    {
      term: 'Deck',
      fullForm: null,
      definition: 'A slide presentation used to pitch creative concepts, strategies, or campaign results to a client.',
      exampleJargon: 'I need the deck polished by 9 AM for the pitch.',
      examplePlain: 'I need the slide presentation polished by 9 AM for the client meeting.',
      difficulty: 1,
    },
    {
      term: 'KPI',
      fullForm: 'Key Performance Indicator',
      definition: 'A metric used to measure whether a campaign is achieving its goals.',
      exampleJargon: 'Reach and engagement rate are the KPIs for the awareness phase of the campaign.',
      examplePlain: 'The number of people we reach and how much they interact with our content are the main measures of success for the awareness portion of the campaign.',
      difficulty: 1,
    },
    {
      term: 'ATL',
      fullForm: 'Above-the-Line',
      definition: 'Broad-reach advertising directed at mass audiences — TV, radio, billboards.',
      exampleJargon: 'The ATL spend is committed — three months of network TV running alongside our digital work.',
      examplePlain: 'The broad-reach TV advertising spend is locked in — three months of network television running alongside our digital campaigns.',
      difficulty: 1,
    },
    {
      term: 'BTL',
      fullForm: 'Below-the-Line',
      definition: 'Targeted, direct marketing efforts aimed at specific audiences — email, direct mail, events.',
      exampleJargon: 'We\'re relying on BTL activation at the retail level to drive trial.',
      examplePlain: 'We\'re relying on targeted, direct-to-consumer activities in stores to get people to try the product.',
      difficulty: 1,
    },
    {
      term: 'Organic',
      fullForm: null,
      definition: 'Unpaid content or traffic that reaches audiences through natural distribution rather than paid placement.',
      exampleJargon: 'Organic engagement on the post was 10x what we expected — clearly struck a nerve.',
      examplePlain: 'Unpaid, naturally distributed engagement on the post was 10 times what we expected — it clearly resonated with people.',
      difficulty: 1,
    },
    {
      term: 'Brand equity',
      fullForm: null,
      definition: 'The value a brand carries beyond its functional attributes, derived from customer perception and loyalty.',
      exampleJargon: 'Twenty years of advertising has built enormous brand equity — consumers trust this name instinctively.',
      examplePlain: 'Twenty years of advertising has built enormous brand value — consumers instinctively trust this company\'s name.',
      difficulty: 2,
    },
    {
      term: 'Bleed',
      fullForm: null,
      definition: 'A design element that extends to the trimmed edge of a printed piece to avoid white borders.',
      exampleJargon: 'Make sure the background image bleeds on all four sides or it\'ll look amateurish when trimmed.',
      examplePlain: 'Make sure the background image extends all the way to the edges on all four sides or it\'ll look unprofessional after the paper is cut.',
      difficulty: 2,
    },
    {
      term: 'Comp',
      fullForm: 'Comprehensive layout',
      definition: 'A mock-up showing a client what the final design will look like before production begins.',
      exampleJargon: 'We sent the client three comps of the print ad to get feedback before going to production.',
      examplePlain: 'We sent the client three mock-ups of the print ad to get feedback before starting production.',
      difficulty: 1,
    },
    {
      term: 'Execution',
      fullForm: null,
      definition: 'An individual application of a master ad concept — the billboard version, the 30-second TV spot, the digital banner.',
      exampleJargon: 'We need five executions of this concept — billboard, :30 TV, :15 pre-roll, banner, and social.',
      examplePlain: 'We need five individual versions of this creative idea — a billboard, a 30-second TV spot, a 15-second online video, a web banner, and a social post.',
      difficulty: 2,
    },
    {
      term: 'Media plan',
      fullForm: null,
      definition: 'A document detailing where, when, and how much money will be spent to place advertising.',
      exampleJargon: 'The media plan is locked — $4M across TV, digital, and OOH for Q3.',
      examplePlain: 'The advertising placement plan is finalized — $4 million across TV, digital, and outdoor advertising for Q3.',
      difficulty: 2,
    },
    {
      term: 'SOW',
      fullForm: 'Statement of Work',
      definition: 'A contract document defining exactly what the agency will deliver, on what timeline, and for what fee.',
      exampleJargon: 'We can\'t start work until the client countersigns the SOW.',
      examplePlain: 'We can\'t start work until the client signs the contract that specifies exactly what we\'ll deliver.',
      difficulty: 2,
    },
    {
      term: 'AOR',
      fullForm: 'Agency of Record',
      definition: 'The primary agency officially designated by a client to handle all or most of their advertising work.',
      exampleJargon: 'We won the AOR assignment after a six-agency pitch — it\'s their entire $50M budget.',
      examplePlain: 'We won the contract to be the client\'s primary advertising agency after competing against six others — it\'s their entire $50 million advertising budget.',
      difficulty: 2,
    },
    {
      term: 'CRM',
      fullForm: 'Customer Relationship Management',
      definition: 'A system for managing and tracking all interactions with current and potential customers.',
      exampleJargon: 'We\'re pulling the customer list from their CRM to build a lookalike audience for the campaign.',
      examplePlain: 'We\'re using the client\'s customer database to find new potential customers who look like their existing ones.',
      difficulty: 2,
    },
    {
      term: 'CPM',
      fullForm: 'Cost Per Mille',
      definition: 'The cost to deliver 1,000 ad impressions to a target audience.',
      exampleJargon: 'Our CPM on this placement is $12 — expensive but the audience quality justifies it.',
      examplePlain: 'Our cost to reach 1,000 people with this ad placement is $12 — expensive but the audience quality justifies it.',
      difficulty: 1,
    },
    {
      term: 'CPC',
      fullForm: 'Cost Per Click',
      definition: 'The amount an advertiser pays each time a user clicks on their ad.',
      exampleJargon: 'We optimized the Google campaign for CPC and got it down to $0.80.',
      examplePlain: 'We fine-tuned the Google ad campaign to lower the amount we pay per click, getting it down to $0.80.',
      difficulty: 1,
    },
    {
      term: 'CTR',
      fullForm: 'Click-Through Rate',
      definition: 'The percentage of people who clicked an ad after seeing it.',
      exampleJargon: 'The CTR on the new creative is 0.4%, double what we were seeing with the old banner.',
      examplePlain: 'The percentage of people clicking the new ad is 0.4%, double what we were getting with the old version.',
      difficulty: 1,
    },
    {
      term: 'ROAS',
      fullForm: 'Return on Ad Spend',
      definition: 'The revenue generated for every dollar spent on advertising.',
      exampleJargon: 'We\'re hitting a 4:1 ROAS on the paid social campaign — $4 in revenue for every $1 spent.',
      examplePlain: 'We\'re generating $4 in sales for every $1 we spend on the paid social campaign.',
      difficulty: 2,
    },
    {
      term: 'PPC',
      fullForm: 'Pay Per Click',
      definition: 'An online advertising model where advertisers pay only when a user clicks their ad.',
      exampleJargon: 'We\'re allocating 30% of the digital budget to PPC to capture in-market demand.',
      examplePlain: 'We\'re allocating 30% of the digital budget to pay-per-click advertising to capture people actively searching for this product.',
      difficulty: 1,
    },
    {
      term: 'SEO',
      fullForm: 'Search Engine Optimization',
      definition: 'The practice of improving a website\'s content and structure to rank higher in unpaid search results.',
      exampleJargon: 'Six months of SEO work moved us from page 3 to page 1 for the top three keywords.',
      examplePlain: 'Six months of improving our website\'s content and structure moved us from the third page of search results to the first for our most important search terms.',
      difficulty: 1,
    },
    {
      term: 'SERP',
      fullForm: 'Search Engine Results Page',
      definition: 'The page a search engine displays in response to a query — where paid and organic results both appear.',
      exampleJargon: 'We own the SERP for our branded terms, but competitors are outranking us for category terms.',
      examplePlain: 'We dominate search results for our own brand name, but competitors are outranking us for generic category searches.',
      difficulty: 2,
    },
    {
      term: 'RTB',
      fullForm: 'Real-Time Bidding',
      definition: 'Automated, millisecond-scale auctions determining which ad is shown to a user when a page loads.',
      exampleJargon: 'All our display is running through RTB now — no more direct deals for standard inventory.',
      examplePlain: 'All our display advertising is now bought through automated, real-time auctions — we no longer negotiate direct deals for standard placements.',
      difficulty: 2,
    },
    {
      term: 'OTT',
      fullForm: 'Over-The-Top',
      definition: 'Video content streamed directly over the internet, bypassing traditional cable or satellite TV.',
      exampleJargon: 'OTT is growing faster than any other channel in the plan — we\'re doubling the allocation next quarter.',
      examplePlain: 'Video streaming is growing faster than any other channel in our plan — we\'re doubling our investment next quarter.',
      difficulty: 2,
    },
    {
      term: 'CTV',
      fullForm: 'Connected TV',
      definition: 'An internet-enabled television device — smart TV, Roku, Fire Stick — used to stream OTT content.',
      exampleJargon: 'We\'re targeting cord-cutters on CTV to reach younger households who no longer have cable.',
      examplePlain: 'We\'re targeting people who have ditched cable TV by advertising on smart TVs and streaming devices.',
      difficulty: 2,
    },
    {
      term: 'OOH',
      fullForm: 'Out-of-Home',
      definition: 'Advertising that reaches consumers outside their homes — billboards, transit ads, airport displays.',
      exampleJargon: 'We booked OOH placements in every launch market — transit shelters, bulletins, and wallscapes.',
      examplePlain: 'We booked outdoor advertising in every launch market — bus shelters, large highway billboards, and building wall ads.',
      difficulty: 1,
    },
    {
      term: 'DSP',
      fullForm: 'Demand-Side Platform',
      definition: 'Software used by advertisers to buy digital ad inventory programmatically across multiple exchanges.',
      exampleJargon: 'Our DSP lets us target the same custom audience across 15 different ad exchanges simultaneously.',
      examplePlain: 'Our ad buying software lets us target the same group of people across 15 different digital advertising networks at the same time.',
      difficulty: 3,
    },
    {
      term: 'SSP',
      fullForm: 'Supply-Side Platform',
      definition: 'Software used by publishers to sell their ad inventory programmatically to the highest bidder.',
      exampleJargon: 'The publisher uses an SSP to maximize revenue by putting its inventory in front of all major buyers at once.',
      examplePlain: 'The publisher uses software that automatically shows its ad space to all major buyers at once to get the highest possible price.',
      difficulty: 3,
    },
    {
      term: 'Programmatic',
      fullForm: null,
      definition: 'The automated, algorithm-driven buying and selling of digital advertising space.',
      exampleJargon: 'Almost all our digital spend is programmatic now — we only negotiate direct deals for high-impact premium placements.',
      examplePlain: 'Almost all our digital advertising is now bought automatically by algorithms — we only negotiate directly with publishers for the most premium spots.',
      difficulty: 2,
    },
    {
      term: 'Retargeting',
      fullForm: null,
      definition: 'Showing ads specifically to users who have previously visited your site or interacted with your brand.',
      exampleJargon: 'Retargeting users who abandoned checkout drove a 15% lift in conversion rate.',
      examplePlain: 'Showing ads to people who had items in their cart but didn\'t buy drove a 15% increase in completed purchases.',
      difficulty: 2,
    },
    {
      term: 'Lookalike audience',
      fullForm: null,
      definition: 'A targeting method that finds new potential customers who share characteristics with your existing customers.',
      exampleJargon: 'We built a lookalike audience from our top 1,000 customers and used it to prospect on Facebook.',
      examplePlain: 'We found Facebook users who share characteristics with our best 1,000 customers and showed them ads to attract new buyers.',
      difficulty: 2,
    },
    {
      term: 'A/B test',
      fullForm: null,
      definition: 'A controlled experiment comparing two versions of an ad or page to determine which performs better.',
      exampleJargon: 'We ran an A/B test on the email subject line and the personalized version won by 22%.',
      examplePlain: 'We tested two versions of the email subject line by sending each to half the list, and the personalized version got 22% more opens.',
      difficulty: 1,
    },
    {
      term: 'Reach',
      fullForm: null,
      definition: 'The total number of unique people who see an ad at least once during a campaign.',
      exampleJargon: 'This buy gives us 85% reach against adults 25-54 in the first two weeks.',
      examplePlain: 'This advertising buy will expose 85% of adults ages 25-54 to our ad at least once in the first two weeks.',
      difficulty: 1,
    },
    {
      term: 'Frequency',
      fullForm: null,
      definition: 'The average number of times a unique user sees the same ad during a campaign period.',
      exampleJargon: 'We\'re capping frequency at 5 exposures per week to avoid ad fatigue.',
      examplePlain: 'We\'re limiting each person to seeing our ad no more than 5 times per week to prevent them from getting tired of it.',
      difficulty: 1,
    },
    {
      term: 'Share of voice',
      fullForm: null,
      definition: 'A brand\'s percentage of total advertising activity within a category compared to its competitors.',
      exampleJargon: 'We increased our share of voice from 12% to 19% — now we\'re the second loudest brand in the category.',
      examplePlain: 'We increased our share of all advertising in this product category from 12% to 19%, making us the second most visible brand.',
      difficulty: 3,
    },
    {
      term: 'GRP',
      fullForm: 'Gross Rating Point',
      definition: 'A unit measuring total advertising weight — reach multiplied by frequency.',
      exampleJargon: 'We\'re buying 400 GRPs per week in the launch markets to build awareness quickly.',
      examplePlain: 'We\'re buying enough TV advertising each week to reach the target audience an average of 4 times, ensuring rapid awareness building.',
      difficulty: 3,
    },
    {
      term: 'Bounce rate',
      fullForm: null,
      definition: 'The percentage of website visitors who leave after viewing only one page without taking any action.',
      exampleJargon: 'Our bounce rate dropped from 68% to 44% after we redesigned the landing page.',
      examplePlain: 'The percentage of visitors who left the website immediately without clicking anything dropped from 68% to 44% after the redesign.',
      difficulty: 2,
    },
    {
      term: 'Native advertising',
      fullForm: null,
      definition: 'Paid content designed to match the look and feel of the editorial content surrounding it.',
      exampleJargon: 'We produced six native advertising articles for the publisher — they match the editorial feel of the site perfectly.',
      examplePlain: 'We created six paid articles for the publisher that are designed to look and feel like regular editorial content on the site.',
      difficulty: 2,
    },
    {
      term: 'UGC',
      fullForm: 'User-Generated Content',
      definition: 'Content created by consumers — photos, reviews, videos — that brands repurpose in their marketing.',
      exampleJargon: 'We\'re incorporating UGC into the campaign — real customer photos outperform our studio shots by 30%.',
      examplePlain: 'We\'re using real photos taken by customers in the campaign — they outperform our professional studio photos by 30%.',
      difficulty: 2,
    },
    {
      term: 'Brand guidelines',
      fullForm: null,
      definition: 'A documented set of rules governing how a brand\'s visual identity, tone, and messaging must be used.',
      exampleJargon: 'Every piece of creative goes through a brand guidelines review before it\'s produced.',
      examplePlain: 'Every piece of advertising is checked against the brand\'s rules for how its name, logo, and messaging must look and sound before production.',
      difficulty: 1,
    },
    {
      term: 'Brand safety',
      fullForm: null,
      definition: 'The practice of ensuring a brand\'s ads do not appear alongside content that could damage its reputation.',
      exampleJargon: 'We\'ve excluded all news and political content to protect brand safety on the programmatic buy.',
      examplePlain: 'We\'ve excluded all news and political websites from our automated ad buying to make sure our ads don\'t appear next to content that could embarrass the brand.',
      difficulty: 3,
    },
    {
      term: 'Retainer',
      fullForm: null,
      definition: 'A recurring fee paid by a client to keep an agency available for ongoing work.',
      exampleJargon: 'We\'re on retainer for $80K a month — that covers all ongoing work outside of project-specific SOWs.',
      examplePlain: 'The client pays us $80,000 per month to remain available for ongoing work, outside of specific project contracts.',
      difficulty: 2,
    },
    {
      term: 'Scope creep',
      fullForm: null,
      definition: 'The gradual expansion of a project\'s deliverables beyond what was defined in the original brief or SOW.',
      exampleJargon: 'The client just added three new deliverables to the project — that\'s scope creep and we need a change order.',
      examplePlain: 'The client just added three items that weren\'t in the original agreement — the project is growing beyond what we contracted for, and we need to update the contract.',
      difficulty: 2,
    },
    {
      term: 'Storyboard',
      fullForm: null,
      definition: 'A sequence of illustrated panels showing the planned visual flow of a video or animated ad.',
      exampleJargon: 'The director needs the approved storyboard by Monday to prep the shot list.',
      examplePlain: 'The director needs the illustrated panel-by-panel plan for the video approved by Monday to plan the shoot.',
      difficulty: 1,
    },
    {
      term: 'Pre-pro',
      fullForm: 'Pre-production',
      definition: 'Everything that happens before a shoot — casting, location scouting, shot listing, prop procurement.',
      exampleJargon: 'Pre-pro is a two-week sprint — casting, location, wardrobe, and prop logistics all have to land simultaneously.',
      examplePlain: 'Everything before the actual shoot is a two-week sprint — casting actors, finding locations, selecting wardrobe, and organizing props all have to come together at once.',
      difficulty: 1,
    },
    {
      term: 'Upfront',
      fullForm: null,
      definition: 'The annual TV marketplace where networks sell the majority of their commercial airtime before the broadcast season.',
      exampleJargon: 'We locked $8M in upfront commitments across three networks before the scatter market opened.',
      examplePlain: 'We committed $8 million in TV advertising space during the annual pre-season TV buying marketplace before the more expensive open market began.',
      difficulty: 3,
    },
    {
      term: 'Pitch',
      fullForm: null,
      definition: 'A formal presentation made by an agency to win a new client or campaign assignment.',
      exampleJargon: 'We won the pitch against four other agencies and took home a $25M account.',
      examplePlain: 'We won the competitive presentation against four other agencies and landed a $25 million advertising account.',
      difficulty: 1,
    },
    {
      term: 'Tearsheet',
      fullForm: null,
      definition: 'A page clipped from a publication and sent to an advertiser as proof their ad ran as placed.',
      exampleJargon: 'The publisher sent tearsheets for all 12 placements as proof of run.',
      examplePlain: 'The publisher sent copies of the actual pages where our ads appeared as proof they ran as planned.',
      difficulty: 3,
    },
    {
      term: 'Above the fold',
      fullForm: null,
      definition: 'Website or print content visible without scrolling — prime real estate for key messages and CTAs.',
      exampleJargon: 'Our CTA is above the fold — users don\'t have to scroll to see it.',
      examplePlain: 'Our call to action is visible on the screen as soon as the page loads — users don\'t have to scroll down to see it.',
      difficulty: 1,
    },
    {
      term: 'Attribution',
      fullForm: null,
      definition: 'The process of determining which marketing touchpoints contributed to a conversion or sale.',
      exampleJargon: 'Multi-touch attribution showed that organic search had been undervalued in our model for years.',
      examplePlain: 'Our analysis of which marketing touchpoints led to sales showed that unpaid search had been getting less credit than it deserved for years.',
      difficulty: 3,
    },
    {
      term: 'Conversion',
      fullForm: null,
      definition: 'A user completing a desired action — a purchase, form fill, or sign-up — as a result of an ad.',
      exampleJargon: 'Our conversion rate improved from 1.2% to 2.8% after the landing page redesign.',
      examplePlain: 'The percentage of visitors who completed a desired action improved from 1.2% to 2.8% after we redesigned the page.',
      difficulty: 1,
    },
    {
      term: 'Engagement rate',
      fullForm: null,
      definition: 'A metric combining likes, shares, comments, and clicks divided by total impressions or reach.',
      exampleJargon: 'The campaign\'s engagement rate of 4.7% was nearly double the industry benchmark.',
      examplePlain: 'The percentage of people who interacted with our campaign content was 4.7%, nearly double the industry average.',
      difficulty: 2,
    },
    {
      term: 'Dark post',
      fullForm: null,
      definition: 'A paid social media ad targeted only to specific audiences that does not appear on the brand\'s public page.',
      exampleJargon: 'We ran 12 dark posts simultaneously, each targeting a different customer segment with different messaging.',
      examplePlain: 'We ran 12 paid social ads at the same time, each targeting a different group with tailored messaging — none visible to anyone outside those specific audiences.',
      difficulty: 3,
    },
    {
      term: 'Insertion order',
      fullForm: null,
      definition: 'A formal, signed agreement between an advertiser and a media outlet specifying the details of an ad buy.',
      exampleJargon: 'The insertion order is signed — we\'re locked into $1.2M in display across their network for Q4.',
      examplePlain: 'The formal advertising contract is signed — we\'re committed to $1.2 million in display advertising across their network for Q4.',
      difficulty: 3,
    },
    {
      term: 'CTA',
      fullForm: 'Call to Action',
      definition: 'A prompt in an ad directing the viewer to take a specific next step — "Shop Now," "Learn More," "Sign Up."',
      exampleJargon: 'Every email ends with a clear CTA — if you don\'t tell them what to do next, they won\'t do it.',
      examplePlain: 'Every email ends with a clear instruction telling readers what action to take — if you don\'t tell people what to do next, they won\'t do it.',
      difficulty: 1,
    },
    {
      term: 'Flighting',
      fullForm: null,
      definition: 'A scheduling strategy in which advertising runs in bursts separated by periods of no activity.',
      exampleJargon: 'We\'re using a flighting strategy — six weeks on, two weeks off — to stretch the budget across a full year.',
      examplePlain: 'We\'re running advertising in bursts — six weeks on, two weeks off — to make the budget last a full year while maintaining impact.',
      difficulty: 3,
    },
    {
      term: 'Scatter',
      fullForm: null,
      definition: 'TV inventory sold outside of the upfront market — typically at a premium and closer to air date.',
      exampleJargon: 'With upfront commitments down industry-wide, we picked up scatter inventory at favorable rates.',
      examplePlain: 'With fewer commitments during the annual pre-season buying period, we bought leftover TV ad space close to air date at better-than-usual prices.',
      difficulty: 3,
    },
  ];

  for (const t of adAgencyTerms) {
    await prisma.term.upsert({
      where: { id: `ad-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}` },
      update: {},
      create: {
        id: `ad-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        industryId: adAgency.id,
        ...t,
      },
    });
  }
  console.log(`Seeded ${adAgencyTerms.length} ad agency terms`);

  // ─── Industry 3: Nonprofit ────────────────────────────────────────────────
  const nonprofit = await prisma.industry.upsert({
    where: { slug: 'nonprofit' },
    update: {},
    create: {
      name: 'Nonprofit',
      slug: 'nonprofit',
      description: 'Fundraising, grant writing, donor relations, and the language of the nonprofit sector.',
      icon: '🤝',
      isActive: true,
    },
  });

  const nonprofitTerms = [
    {
      term: 'Development',
      fullForm: null,
      definition: 'The fundraising function of a nonprofit — all activities aimed at securing contributed revenue.',
      exampleJargon: 'Our development team hit 112% of goal this fiscal year — best performance in a decade.',
      examplePlain: 'Our fundraising team raised 112% of their goal this fiscal year — the best performance in a decade.',
      difficulty: 1,
    },
    {
      term: 'Annual fund',
      fullForm: null,
      definition: 'An ongoing fundraising program that seeks general operating support contributions each year.',
      exampleJargon: 'Annual fund donors are our most reliable revenue source — 3,000 gifts averaging $150.',
      examplePlain: 'Our yearly fundraising program for general operating support is our most reliable income — 3,000 donations averaging $150 each.',
      difficulty: 1,
    },
    {
      term: 'Major gift',
      fullForm: null,
      definition: 'A large donation requiring long-term personal cultivation — typically representing a significant share of a campaign goal.',
      exampleJargon: 'She\'s been in cultivation for three years and is finally ready for a major gift ask.',
      examplePlain: 'She\'s been receiving personal outreach from our staff for three years and is finally ready to be asked for a large donation.',
      difficulty: 2,
    },
    {
      term: 'In-kind',
      fullForm: null,
      definition: 'A non-cash contribution of goods, services, or professional expertise rather than money.',
      exampleJargon: 'The law firm provided in-kind legal services valued at $40,000 — a huge help on the contract negotiations.',
      examplePlain: 'The law firm provided free legal services worth $40,000 instead of donating cash — a huge help on the contract negotiations.',
      difficulty: 1,
    },
    {
      term: 'Unrestricted funds',
      fullForm: null,
      definition: 'Donations with no donor-imposed conditions — the organization can use them for any purpose.',
      exampleJargon: 'We desperately need unrestricted funds to cover operating overhead — restricted grants only go so far.',
      examplePlain: 'We desperately need donations with no strings attached to cover operating costs — grants restricted to specific programs only go so far.',
      difficulty: 1,
    },
    {
      term: 'Restricted funds',
      fullForm: null,
      definition: 'Donations designated by the donor for a specific purpose — cannot be redirected to general operations.',
      exampleJargon: 'The restricted funds from the Gates grant can only be spent on the youth coding program.',
      examplePlain: 'The donated money from the Gates grant can only be used for the youth coding program, as the donor specified.',
      difficulty: 2,
    },
    {
      term: 'Matching gift',
      fullForm: null,
      definition: 'A corporate program that matches an employee\'s charitable donation, doubling or multiplying the gift\'s impact.',
      exampleJargon: 'We launched a matching gift drive — every dollar raised in December is doubled by a lead donor.',
      examplePlain: 'We launched a fundraising drive where every dollar donated in December is matched with an equal amount from a generous lead donor.',
      difficulty: 1,
    },
    {
      term: 'Stewardship',
      fullForm: null,
      definition: 'The ongoing practice of acknowledging, communicating with, and deepening relationships with donors after their gift.',
      exampleJargon: 'Good stewardship is why our donor retention rate is 65% — we treat every donor like a major donor.',
      examplePlain: 'Taking care of our donors after they give — sending thank-yous, sharing impact stories, staying in touch — is why 65% of them give again.',
      difficulty: 2,
    },
    {
      term: 'Cultivation',
      fullForm: null,
      definition: 'The relationship-building process with a prospective major donor before a gift ask is ever made.',
      exampleJargon: 'We spent 18 months in cultivation before asking him for the $500,000 gift.',
      examplePlain: 'We spent 18 months building a relationship and deepening his connection to our mission before asking him to donate $500,000.',
      difficulty: 2,
    },
    {
      term: 'Case for support',
      fullForm: null,
      definition: 'A compelling document or narrative articulating why donors should invest in an organization\'s mission.',
      exampleJargon: 'Before the capital campaign, we spent six months building our case for support with focus groups and donor interviews.',
      examplePlain: 'Before the major fundraising drive, we spent six months developing a compelling argument for why donors should invest in our cause.',
      difficulty: 2,
    },
    {
      term: 'Prospect research',
      fullForm: null,
      definition: 'The practice of gathering biographical and financial data on potential donors to inform ask amounts and strategy.',
      exampleJargon: 'Prospect research flagged three new major gift prospects from the gala attendee list.',
      examplePlain: 'Researching the background and financial capacity of potential donors identified three new people from our gala guest list who could give significant amounts.',
      difficulty: 2,
    },
    {
      term: 'LYBUNT',
      fullForm: 'Last Year But Unfortunately Not This',
      definition: 'A donor who gave last year but has not yet given this year — a high-priority re-engagement segment.',
      exampleJargon: 'Our LYBUNT rate is 35% — we\'re losing too many donors from year one to year two.',
      examplePlain: '35% of last year\'s donors haven\'t given yet this year — we\'re losing too many donors in their second year.',
      difficulty: 2,
    },
    {
      term: 'SYBUNT',
      fullForm: 'Some Year But Unfortunately Not This',
      definition: 'A donor who gave in a prior year but not in the current fiscal year — a lapsed donor worth recultivating.',
      exampleJargon: 'We ran a special SYBUNT campaign to reactivate 500 lapsed donors before fiscal year end.',
      examplePlain: 'We ran a special campaign to win back 500 donors who gave in prior years but haven\'t given recently.',
      difficulty: 2,
    },
    {
      term: 'Pledge',
      fullForm: null,
      definition: 'A formal commitment by a donor to make a gift — often over multiple years — that is legally or morally binding.',
      exampleJargon: 'The board member made a three-year pledge of $50,000 per year for the capital campaign.',
      examplePlain: 'The board member formally committed to donating $50,000 per year for three years for the major fundraising initiative.',
      difficulty: 1,
    },
    {
      term: 'Bequest',
      fullForm: null,
      definition: 'A gift made as part of a donor\'s will or estate plan that the organization receives after the donor\'s death.',
      exampleJargon: 'She included the organization in her will as a bequest — we won\'t receive the gift for years but it\'s documented.',
      examplePlain: 'She included the organization in her will — we won\'t receive the money until she passes away, but it\'s formally documented.',
      difficulty: 2,
    },
    {
      term: 'Planned giving',
      fullForm: null,
      definition: 'Charitable contributions structured as part of a donor\'s long-term financial or estate arrangements.',
      exampleJargon: 'We launched a planned giving program to capture legacy gifts from our most committed donors.',
      examplePlain: 'We launched a program to encourage our most loyal donors to include us in their wills or long-term financial plans.',
      difficulty: 3,
    },
    {
      term: 'Capital campaign',
      fullForm: null,
      definition: 'A time-limited, goal-driven fundraising initiative to raise major funds for a specific purpose — a building, endowment, or program.',
      exampleJargon: 'We\'re in the quiet phase of a $50M capital campaign for the new performing arts center.',
      examplePlain: 'We\'re in the early, private phase of a $50 million major fundraising drive for the new arts building, focused on securing lead gifts before going public.',
      difficulty: 2,
    },
    {
      term: 'Endowment',
      fullForm: null,
      definition: 'A permanently invested fund whose annual income provides ongoing financial support to the organization.',
      exampleJargon: 'The endowment now generates $1.2M annually — enough to cover our entire education program budget.',
      examplePlain: 'Our permanently invested fund now generates $1.2 million in interest and returns each year — enough to fund our entire education program.',
      difficulty: 2,
    },
    {
      term: 'RFP',
      fullForm: 'Request for Proposal',
      definition: 'A document issued by a funder soliciting grant applications or bids for a specific opportunity.',
      exampleJargon: 'The foundation issued an RFP for mental health programs serving underserved youth.',
      examplePlain: 'The foundation put out a formal call for grant applications for mental health programs serving underserved young people.',
      difficulty: 1,
    },
    {
      term: 'LOI',
      fullForm: 'Letter of Intent',
      definition: 'A brief preliminary document expressing interest in a grant before a full proposal is invited.',
      exampleJargon: 'We submitted an LOI to the foundation and were invited to submit a full proposal.',
      examplePlain: 'We submitted a brief expression of interest to the foundation and were invited to develop a full grant application.',
      difficulty: 2,
    },
    {
      term: '501(c)(3)',
      fullForm: null,
      definition: 'The IRS tax code designation for a charitable, tax-exempt nonprofit organization.',
      exampleJargon: 'Your donation is tax-deductible because we are a 501(c)(3) organization.',
      examplePlain: 'Your donation is tax-deductible because we are a federally recognized tax-exempt charitable organization.',
      difficulty: 1,
    },
    {
      term: 'Form 990',
      fullForm: null,
      definition: 'The annual public information return that nonprofits file with the IRS, disclosing finances, programs, and governance.',
      exampleJargon: 'Anyone can look up our Form 990 on Candid to see our financials and top salaries.',
      examplePlain: 'Anyone can look up our annual public financial filing on a nonprofit watchdog website to see how we spend our money.',
      difficulty: 2,
    },
    {
      term: 'Theory of change',
      fullForm: null,
      definition: 'A framework mapping how an organization\'s activities and outputs are expected to lead to long-term social outcomes.',
      exampleJargon: 'Our theory of change links after-school tutoring directly to improved graduation rates through evidence-backed outcomes.',
      examplePlain: 'Our explanation of how our programs work maps how after-school tutoring leads to better grades and then higher graduation rates, supported by research.',
      difficulty: 3,
    },
    {
      term: 'Logic model',
      fullForm: null,
      definition: 'A visual representation of a program\'s inputs, activities, outputs, and intended outcomes.',
      exampleJargon: 'The board asked us to develop a logic model for the new program before the next grant report.',
      examplePlain: 'The board asked us to create a visual diagram showing what resources we put in, what activities we run, and what outcomes we expect before the next grant report.',
      difficulty: 2,
    },
    {
      term: 'Impact metrics',
      fullForm: null,
      definition: 'Quantitative and qualitative measurements used to demonstrate the effectiveness and outcomes of a program.',
      exampleJargon: 'Our impact metrics show a 40% reduction in emergency room visits among program participants.',
      examplePlain: 'Our measurements of program effectiveness show a 40% decrease in emergency room visits among people who went through our program.',
      difficulty: 2,
    },
    {
      term: 'Capacity building',
      fullForm: null,
      definition: 'Investment in an organization\'s systems, people, or infrastructure to increase its ability to fulfill its mission.',
      exampleJargon: 'The foundation grant is specifically for capacity building — they want us to invest in our data systems, not program delivery.',
      examplePlain: 'The foundation grant is specifically to strengthen our organization — they want us to upgrade our data tracking systems, not just run more programs.',
      difficulty: 2,
    },
    {
      term: 'DAF',
      fullForm: 'Donor-Advised Fund',
      definition: 'A charitable investment account through which donors recommend grants to nonprofits over time.',
      exampleJargon: 'She made the gift through her DAF at Fidelity Charitable — we received the check within a week.',
      examplePlain: 'She donated through her donor-advised fund — a special charitable account she maintains at Fidelity — and we received the funds within a week.',
      difficulty: 3,
    },
    {
      term: 'Moves management',
      fullForm: null,
      definition: 'A structured system for tracking and planning each step of a donor relationship from identification through the gift.',
      exampleJargon: 'We use moves management in our CRM to track every touchpoint with each major gift prospect.',
      examplePlain: 'We use a systematic tracking system in our donor database to document every interaction with each potential major donor.',
      difficulty: 3,
    },
    {
      term: 'Prospect pipeline',
      fullForm: null,
      definition: 'The full pool of potential donors at various stages of identification, cultivation, solicitation, and stewardship.',
      exampleJargon: 'The major gift officer presented her prospect pipeline — 12 donors in active cultivation and three ready for an ask.',
      examplePlain: 'The major gifts fundraiser presented her list of potential major donors — 12 in active relationship-building and three ready to be asked for a gift.',
      difficulty: 2,
    },
    {
      term: 'Ask',
      fullForm: null,
      definition: 'The direct solicitation of a gift — the moment when the fundraiser requests a specific dollar amount from a donor.',
      exampleJargon: 'The ask went well — she said yes to $25,000 for the scholarship fund.',
      examplePlain: 'The direct conversation where we requested a donation went well — she agreed to give $25,000 for scholarships.',
      difficulty: 1,
    },
    {
      term: 'Upgrade',
      fullForm: null,
      definition: 'A solicitation strategy aimed at getting a current donor to give more than they gave last time.',
      exampleJargon: 'We\'re focusing the spring campaign on upgrading $100–$500 donors to the $1,000 leadership giving level.',
      examplePlain: 'We\'re focusing our spring campaign on convincing donors who give $100–$500 to increase to the $1,000 leadership giving level.',
      difficulty: 2,
    },
    {
      term: 'Recurring donor',
      fullForm: null,
      definition: 'A donor who makes automatic gifts on a regular schedule — monthly or annually.',
      exampleJargon: 'We converted 200 one-time donors to recurring donors this year, significantly stabilizing our revenue.',
      examplePlain: 'We convinced 200 people who had made single donations to set up automatic monthly giving, making our income much more predictable.',
      difficulty: 1,
    },
    {
      term: 'Peer-to-peer fundraising',
      fullForm: null,
      definition: 'A strategy in which supporters solicit donations from their own personal networks on the organization\'s behalf.',
      exampleJargon: 'The birthday peer-to-peer fundraising campaign raised $18,000 and brought in 45 new donors we\'d never reached before.',
      examplePlain: 'The fundraising campaign where supporters asked their friends to donate in their honor raised $18,000 and brought in 45 donors we\'d never heard of.',
      difficulty: 1,
    },
    {
      term: 'Board governance',
      fullForm: null,
      definition: 'The policies, structures, and fiduciary responsibilities through which a nonprofit\'s board of directors provides oversight.',
      exampleJargon: 'Strong board governance is what prevented any fiscal crisis when the executive director suddenly resigned.',
      examplePlain: 'Strong oversight policies and fiduciary responsibility from the board of directors prevented a crisis when the executive director suddenly left.',
      difficulty: 3,
    },
    {
      term: 'Board give or get',
      fullForm: null,
      definition: 'An informal policy requiring board members to either personally donate or raise a set dollar amount each year.',
      exampleJargon: 'The board give or get policy sets a $10,000 minimum — every member either donates it or raises it.',
      examplePlain: 'Our board policy requires every board member to either personally donate $10,000 or raise that amount from others each year.',
      difficulty: 2,
    },
    {
      term: 'Fiscal sponsorship',
      fullForm: null,
      definition: 'An arrangement in which an established 501(c)(3) legally sponsors an unincorporated project, enabling it to receive tax-deductible donations.',
      exampleJargon: 'The neighborhood arts collective operates under fiscal sponsorship through a larger 501(c)(3) while it builds its own infrastructure.',
      examplePlain: 'The neighborhood arts group runs under the legal and financial umbrella of an established nonprofit while it builds up enough structure to become independent.',
      difficulty: 3,
    },
    {
      term: 'Program officer',
      fullForm: null,
      definition: 'A staff member at a foundation who manages the grantmaking process — the person grant seekers typically pitch to.',
      exampleJargon: 'We\'ve had three coffee meetings with the program officer — she\'s very interested in our model.',
      examplePlain: 'We\'ve met three times with the foundation staff member who manages the grants process — she\'s genuinely interested in what we do.',
      difficulty: 2,
    },
    {
      term: 'Site visit',
      fullForm: null,
      definition: 'A funder\'s in-person visit to a nonprofit to evaluate its programs before making a grant decision.',
      exampleJargon: 'The foundation scheduled a site visit for next month — we need to make sure the program staff is prepared.',
      examplePlain: 'The foundation is sending someone to visit our organization in person next month before deciding on a grant — we need our program staff ready.',
      difficulty: 2,
    },
    {
      term: 'Challenge grant',
      fullForm: null,
      definition: 'A gift contingent on the organization raising a matching amount from other donors — used to motivate broader giving.',
      exampleJargon: 'A lead donor offered a $500,000 challenge grant — every new dollar raised in the campaign is matched.',
      examplePlain: 'A major donor pledged $500,000 that will only be released if we raise an equal amount from other donors — designed to motivate more giving.',
      difficulty: 2,
    },
    {
      term: 'Naming opportunity',
      fullForm: null,
      definition: 'The right for a donor to have a building, room, or program bear their name in recognition of a significant gift.',
      exampleJargon: 'We offered a naming opportunity for the new building wing in exchange for a $2M gift.',
      examplePlain: 'We offered a donor the right to have the new building wing named after them in exchange for a $2 million donation.',
      difficulty: 2,
    },
    {
      term: 'Gift acceptance policy',
      fullForm: null,
      definition: 'An organization\'s formal rules governing which types of gifts it will accept and how they are valued.',
      exampleJargon: 'Our gift acceptance policy prohibits accepting real estate without a prior environmental review.',
      examplePlain: 'Our organization\'s formal rules about what donations we\'ll take specify that we won\'t accept real estate without an environmental assessment.',
      difficulty: 3,
    },
    {
      term: 'Annual appeal',
      fullForm: null,
      definition: 'A direct mail or email solicitation sent to all donors and prospects at least once a year asking for a contribution.',
      exampleJargon: 'The year-end annual appeal is our largest fundraising event — it accounts for 40% of our individual giving.',
      examplePlain: 'The fundraising letter we send to all donors at year-end is our biggest income event — it accounts for 40% of all individual donations.',
      difficulty: 1,
    },
    {
      term: 'Recognition society',
      fullForm: null,
      definition: 'A formal donor loyalty program that publicly honors contributors who give at or above a defined threshold.',
      exampleJargon: 'Donors who give $1,000 or more are invited into our recognition society, The Founders Circle.',
      examplePlain: 'Donors who give $1,000 or more are invited into our formal donor loyalty program, called The Founders Circle, which offers special recognition.',
      difficulty: 2,
    },
    {
      term: 'Federated campaign',
      fullForm: null,
      definition: 'A joint fundraising effort in which a central nonprofit collects donations and distributes them to member organizations — United Way is the classic example.',
      exampleJargon: 'We receive annual allocations through the local federated campaign, which handles workplace giving in this region.',
      examplePlain: 'We receive annual funding through a joint fundraising organization in our area that collects workplace payroll donations and distributes them to member charities.',
      difficulty: 3,
    },
    {
      term: 'Community foundation',
      fullForm: null,
      definition: 'A public charitable organization that manages a collection of funds established by donors in a specific geographic area.',
      exampleJargon: 'We applied for a grant through the community foundation, which pools donor funds from across the county.',
      examplePlain: 'We applied for a grant through the regional foundation that pools together donated funds from many local donors and distributes them to nonprofits in the area.',
      difficulty: 2,
    },
    {
      term: 'Blended gift',
      fullForm: null,
      definition: 'A combination of a current cash gift and a future planned gift structured together as part of one donor relationship.',
      exampleJargon: 'The donor made a blended gift — $50,000 this year plus a $500,000 bequest in her will.',
      examplePlain: 'The donor made a combination gift — $50,000 in cash right now plus a $500,000 gift left in her will for after she passes.',
      difficulty: 3,
    },
    {
      term: 'CSR',
      fullForm: 'Corporate Social Responsibility',
      definition: 'A company\'s commitment to social and environmental causes — often the lens through which corporations decide which nonprofits to support.',
      exampleJargon: 'Their CSR program focuses on education and environment — a perfect fit for our mission.',
      examplePlain: 'Their corporate social responsibility program focuses on education and the environment — which aligns perfectly with what we do.',
      difficulty: 2,
    },
    {
      term: 'Impact investing',
      fullForm: null,
      definition: 'Investing in organizations or funds with the intention of generating measurable social or environmental benefit alongside financial returns.',
      exampleJargon: 'The family office shifted from traditional grantmaking to impact investing to achieve both financial returns and social outcomes.',
      examplePlain: 'The wealthy family\'s foundation switched from simply making grants to also making investments in organizations that can generate both financial returns and positive social change.',
      difficulty: 3,
    },
    {
      term: 'Collective impact',
      fullForm: null,
      definition: 'A framework for cross-sector organizations to coordinate around a shared agenda to solve a specific social problem.',
      exampleJargon: 'The initiative is a collective impact effort — 15 organizations sharing data and working toward a single educational attainment goal.',
      examplePlain: 'The initiative brings 15 organizations together in a coordinated, data-driven effort to achieve a single shared goal around improving educational outcomes.',
      difficulty: 3,
    },
    {
      term: 'Cause marketing',
      fullForm: null,
      definition: 'A collaborative marketing strategy between a for-profit business and a nonprofit to promote a shared cause.',
      exampleJargon: 'The coffee brand ran a cause marketing campaign where 10% of every purchase went to our literacy programs.',
      examplePlain: 'The coffee brand ran a campaign promoting that 10% of every sale would be donated to our reading programs — benefiting both their brand image and our fundraising.',
      difficulty: 2,
    },
    {
      term: 'Solicitation',
      fullForm: null,
      definition: 'Any direct communication asking a donor or prospect for a gift.',
      exampleJargon: 'Every solicitation is personalized — we never send a form letter to a major donor prospect.',
      examplePlain: 'Every donation request is personalized — we never send a generic mass letter to someone with major gift potential.',
      difficulty: 1,
    },
    {
      term: 'Donor retention rate',
      fullForm: null,
      definition: 'The percentage of donors from one year who give again the following year — a key development health metric.',
      exampleJargon: 'Our donor retention rate is 58% — well above the sector average of 43%.',
      examplePlain: '58% of our donors who gave last year have already given again this year — well above the nonprofit average of 43%.',
      difficulty: 2,
    },
    {
      term: 'Mid-level donor',
      fullForm: null,
      definition: 'A donor whose giving falls between the mass annual fund and the major gifts threshold — often underserved but high-potential.',
      exampleJargon: 'We launched a mid-level donor program to give $500–$4,999 donors more personalized stewardship.',
      examplePlain: 'We created a special program for donors who give between $500 and $4,999, offering them more personal attention than our mass annual fund donors get.',
      difficulty: 2,
    },
    {
      term: 'Grateful patient program',
      fullForm: null,
      definition: 'A healthcare fundraising strategy that identifies patients who had positive experiences as potential major gift prospects.',
      exampleJargon: 'The hospital\'s grateful patient program identified 300 potential major gift prospects from patient satisfaction surveys.',
      examplePlain: 'The hospital\'s program that finds patients who had positive experiences and might want to give back identified 300 people who could be major donors.',
      difficulty: 3,
    },
    {
      term: 'Principal gift',
      fullForm: null,
      definition: 'A transformational gift — typically seven figures or more — that significantly changes an organization\'s trajectory.',
      exampleJargon: 'The university received a $50M principal gift — transformational for their endowment campaign.',
      examplePlain: 'The university received a $50 million donation — a transformational amount that significantly advanced their major fundraising drive.',
      difficulty: 3,
    },
    {
      term: 'MOU',
      fullForm: 'Memorandum of Understanding',
      definition: 'A non-binding agreement between two organizations outlining the terms of a planned partnership or collaboration.',
      exampleJargon: 'We signed an MOU with the city housing authority to formalize the partnership before drafting the full contract.',
      examplePlain: 'We signed a non-binding agreement with the city housing authority to outline our planned partnership before drafting the formal contract.',
      difficulty: 2,
    },
    {
      term: 'Program-related investment',
      fullForm: null,
      definition: 'A loan or equity investment made by a foundation to a nonprofit or social enterprise in furtherance of the foundation\'s mission.',
      exampleJargon: 'The foundation made a $1M program-related investment in our social enterprise spinoff.',
      examplePlain: 'The foundation made a $1 million loan to our social enterprise that earns a small interest return while advancing the foundation\'s charitable mission.',
      difficulty: 3,
    },
    {
      term: 'Grant report',
      fullForm: null,
      definition: 'A formal document submitted to a funder after a grant period documenting how funds were used and what outcomes were achieved.',
      exampleJargon: 'The grant report is due in 30 days — we need outcome data from all six program sites.',
      examplePlain: 'The formal document we owe the funder documenting how we used their grant money is due in 30 days — we need data from all six program locations.',
      difficulty: 1,
    },
    {
      term: 'Constituency',
      fullForm: null,
      definition: 'The full community of people connected to a nonprofit — donors, volunteers, clients, alumni, and advocates.',
      exampleJargon: 'Our constituency includes not just donors but also program participants, alumni, and community advocates.',
      examplePlain: 'Our community includes not just the people who give us money, but also everyone who uses our programs, our alumni, and community members who support our cause.',
      difficulty: 1,
    },
    {
      term: 'Bridge funding',
      fullForm: null,
      definition: 'Short-term financing used to cover operating expenses while waiting for a grant payment or other revenue to arrive.',
      exampleJargon: 'We secured $200,000 in bridge funding from a board member while waiting for the state grant payment.',
      examplePlain: 'A board member lent us $200,000 to cover operating expenses while we waited for a delayed state grant check.',
      difficulty: 3,
    },
  ];

  for (const t of nonprofitTerms) {
    await prisma.term.upsert({
      where: { id: `np-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}` },
      update: {},
      create: {
        id: `np-${t.term.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
        industryId: nonprofit.id,
        ...t,
      },
    });
  }
  console.log(`Seeded ${nonprofitTerms.length} nonprofit terms`);

  const total = biotechTerms.length + adAgencyTerms.length + nonprofitTerms.length;
  console.log(`\n✅ Seed complete: 3 industries, ${total} total terms`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
